service: nzshm22-hazard-graphql-api
configValidationMode: error

plugins:
  - serverless-wsgi
  - serverless-plugin-warmup
package:
  individually: false
  patterns:
    - '!__pycache__/**'
    - '!.git/**'
    - '!.github/**'
    - '!.pytest_cache/**'
    - '!.mypy_cache/**'
    - '!.tox/**'
    - '!dist/**'
    - '!docs/**'
    - '!/**'
    - '!node_modules/**'
    - '!package.json'
    - '!package-log.json'
    - '!tests/**'
    - '!site/**'
    - nshm_hazard_graphql_api/**

custom:
  #serverless-wsgi settings, needed for local testing with `serverless wsgi serve`
  wsgi:
    app: nshm_hazard_graphql_api.nshm_hazard_graphql_api.app
    packRequirements: false
    pythonBin: python3
  #serverless-s3-local settings
  s3:
    host: localhost
    directory: /tmp

  # Lambda warmer see https://www.serverless.com/plugins/serverless-plugin-warmup
  warmup:
    littleWarmer:
      enabled: true
      events:
        - schedule: rate(5 minutes)
      concurrency: 1

# DRY constants: define all compound/generated names in one place
# Override args are: .. defaults:
# --app_acroym          signed-uploader
# --s3_bucket           self:custom.app_acronym
# --s3_key_base         self:custom.stage
# --region              us-east-1
# --stage               test
# --deletion_policy     delete

  app_acronym: ${opt:acronym, self:service}
  default_stage: local
  stage: ${opt:stage, self:custom.default_stage}
  stack_name: ${self:custom.app_acronym}-${self:custom.stage}
  region: ${opt:region, self:provider.region}
  deletion_policy: Delete
  # presigned URL TTL
  url_default_ttl: 60

  # Default to using app_acronym as bucket name
  s3_bucket: ${opt:s3_bucket, self:custom.app_acronym}-${self:custom.stage}
  # default to using ${stage} as key base path, keeps stages from namespace collisions
  s3_bucket_arn: arn:aws:s3:::${self:custom.s3_bucket}
  s3_role_resource: ${self:custom.s3_bucket_arn}

provider:
  name: aws
  runtime: python3.11
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      app_image_0:
        path: "."
        file: Dockerfile
        buildArgs:
          STAGE: ${self:custom.stage}
        cacheFrom:
          # - my-image:latest
        platform: linux/amd64

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    apiKeys:
      - name: ${self:custom.stack_name}-TempApiKey-${self:custom.stage}
        description: Api key until we have an auth function # Optional

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
             - "cloudwatch:PutMetricData"
          Resource: "*"
        - Effect: Allow
          Action:
             - "dynamodb:Scan"
             - "dynamodb:DescribeTable"
             - "dynamodb:GetItem"
             - "dynamodb:ConditionCheckItem"
             - "dynamodb:Query"
          Resource:
             - "arn:aws:dynamodb:ap-southeast-2:461564345538:table/THS_HazardAggregation-PROD"
             - "arn:aws:dynamodb:ap-southeast-2:461564345538:table/THS_GriddedHazard-PROD"
        - Effect: Allow
          Action:
            # - s3:*
            - "s3:GetLifecycleConfiguration"
            - "s3:GetBucketTagging"
            - "s3:GetInventoryConfiguration"
            - "s3:GetObjectVersionTagging"
            - "s3:ListBucketVersions"
            - "s3:GetBucketLogging"
            # - "s3:ReplicateTags"
            - "s3:ListBucket"
            - "s3:GetBucketPolicy"
            - "s3:GetObjectVersionTorrent"
            - "s3:GetObjectAcl"
            - "s3:GetEncryptionConfiguration"
            - "s3:GetBucketObjectLockConfiguration"
            - "s3:GetIntelligentTieringConfiguration"
            # - "s3:PutBucketTagging"
            - "s3:GetBucketRequestPayment"
            - "s3:GetObjectVersionAcl"
            - "s3:GetObjectTagging"
            - "s3:GetMetricsConfiguration"
            - "s3:GetBucketOwnershipControls"
            # - "s3:PutObjectTagging"
            # - "s3:DeleteObject"
            # - "s3:PutObjectAcl"
            - "s3:GetBucketPublicAccessBlock"
            - "s3:GetBucketPolicyStatus"
            - "s3:ListBucketMultipartUploads"
            - "s3:GetObjectRetention"
            - "s3:GetBucketWebsite"
            # - "s3:PutObjectVersionTagging"
            - "s3:GetBucketVersioning"
            - "s3:GetBucketAcl"
            - "s3:GetObjectLegalHold"
            - "s3:GetBucketNotification"
            - "s3:GetReplicationConfiguration"
            - "s3:ListMultipartUploadParts"
            # - "s3:PutObject"
            - "s3:GetObject"
            - "s3:GetObjectTorrent"
            # - "s3:PutObjectVersionAcl"
            - "s3:GetBucketCORS"
            - "s3:GetObjectVersionForReplication"
            - "s3:GetBucketLocation"
            - "s3:GetObjectVersion"
          Resource:
            - arn:aws:s3:::ths-dataset-prod
            - arn:aws:s3:::ths-dataset-prod/*
        - Effect: Allow
          Action:
            - ecr:GetDownloadUrlForLayer
            - ecr:BatchGetImage
          Resource:
            - "arn:aws:ecr:*:461564345538:repository/*"

functions:
  app:
    image:
      name: app_image_0
      command:
        - nshm_hazard_graphql_api.handler.handler
      entryPoint:
        - '/lambda-entrypoint.sh'

    description: The graphql API of ${self:service}
    memorySize: 4096 # optional, in MB, default is 1024
    timeout: 20 # optional, in seconds, default is 6
    events:
      - http:
          path: graphql
          method: OPTIONS
      - http:
          path: graphql
          method: POST
          private: true
      - http:
          path: graphql
          method: GET
          private: true
    environment:
      STACK_NAME: ${self:custom.stack_name}
      REGION: ${self:custom.region}
      URL_DEFAULT_TTL: ${self:custom.url_default_ttl}
      DEPLOYMENT_STAGE: ${self:custom.stage}
      ENABLE_METRICS: ${env:ENABLE_METRICS, 'True'}
      COLOR_SCALE_NORMALISATION: ${env:COLOR_SCALE_NORMALISATION, 'LIN'}
      NZSHM22_HAZARD_STORE_STAGE: PROD
      NZSHM22_HAZARD_STORE_REGION: ${self:custom.region}
      DATASET_AGGR_ENABLED: ${env:DATASET_AGGR_ENABLED, 'True'}
      DATASET_AGGR_URI: ${env:DATASET_AGGR_URI, 's3://ths-dataset-prod/NZSHM22_AGG'}
      MPLCONFIGDIR: /tmp

    warmup:
      littleWarmer:
        enabled:
          - test
          - prod
